sudo: false
language: c
compiler:
 - gcc
 - clang
addons:
  apt:
    packages:
     - ed
script: export CC="$CC -std=c99" PATH="$HOME/bin:$PATH" && ./configure -d && make -k test
after_failure: cat tests/summary.log
